BASE=/opt/project/translation/transformer-nmt
DATA=${BASE}/pretokenized_corpus
FILE=corpus_sample.train.tok
python train_sentencepiece.py --path ${DATA} --file ${FILE}
SPM=${BASE}/sentencepiece/build/src/spm_encode
EN_MODEL=${BASE}/prepare_corpus/spc_model/en.bpe.model
KO_MODEL=${BASE}/prepare_corpus/spc_model/ko.bpe.model
SPM_DATA=${BASE}/spm_pretok_corpus
TRAIN=train
VALID=valid
TEST=test
SRC=en
TGT=ko
${SPM} --model=${EN_MODEL} < ${DATA}/corpus_sample.${TRAIN}.tok.${SRC} > ${SPM_DATA}/${TRAIN}.spm.${SRC} &
${SPM} --model=${KO_MODEL} < ${DATA}/corpus_sample.${TRAIN}.tok.${TGT} > ${SPM_DATA}/${TRAIN}.spm.${TGT} &
${SPM} --model=${EN_MODEL} < ${DATA}/corpus_sample.${VALID}.tok.${SRC} > ${SPM_DATA}/${VALID}.spm.${SRC} &
${SPM} --model=${KO_MODEL} < ${DATA}/corpus_sample.${VALID}.tok.${TGT} > ${SPM_DATA}/${VALID}.spm.${TGT} &
${SPM} --model=${EN_MODEL} < ${DATA}/corpus_sample.${TEST}.tok.${SRC} > ${SPM_DATA}/${TEST}.spm.${SRC} &
${SPM} --model=${KO_MODEL} < ${DATA}/corpus_sample.${TEST}.tok.${TGT} > ${SPM_DATA}/${TEST}.spm.${TGT} &
